# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VndkAbiDump.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='VndkAbiDump.proto',
  package='android.vts',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x11VndkAbiDump.proto\x12\x0b\x61ndroid.vts\"h\n\x0bVTableEntry\x12\x0e\n\x06offset\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x16\n\x0e\x64\x65mangled_name\x18\x03 \x01(\t\x12\x12\n\nis_inlined\x18\x04 \x01(\x08\x12\x0f\n\x07is_pure\x18\x05 \x01(\x08\"`\n\x06VTable\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0e\x64\x65mangled_name\x18\x02 \x01(\t\x12\x30\n\x0evtable_entries\x18\x03 \x03(\x0b\x32\x18.android.vts.VTableEntry\"/\n\x07\x41\x62iDump\x12$\n\x07vtables\x18\x01 \x03(\x0b\x32\x13.android.vts.VTable')
)




_VTABLEENTRY = _descriptor.Descriptor(
  name='VTableEntry',
  full_name='android.vts.VTableEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='offset', full_name='android.vts.VTableEntry.offset', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='android.vts.VTableEntry.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='demangled_name', full_name='android.vts.VTableEntry.demangled_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_inlined', full_name='android.vts.VTableEntry.is_inlined', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_pure', full_name='android.vts.VTableEntry.is_pure', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=138,
)


_VTABLE = _descriptor.Descriptor(
  name='VTable',
  full_name='android.vts.VTable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='android.vts.VTable.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='demangled_name', full_name='android.vts.VTable.demangled_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vtable_entries', full_name='android.vts.VTable.vtable_entries', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=236,
)


_ABIDUMP = _descriptor.Descriptor(
  name='AbiDump',
  full_name='android.vts.AbiDump',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vtables', full_name='android.vts.AbiDump.vtables', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=285,
)

_VTABLE.fields_by_name['vtable_entries'].message_type = _VTABLEENTRY
_ABIDUMP.fields_by_name['vtables'].message_type = _VTABLE
DESCRIPTOR.message_types_by_name['VTableEntry'] = _VTABLEENTRY
DESCRIPTOR.message_types_by_name['VTable'] = _VTABLE
DESCRIPTOR.message_types_by_name['AbiDump'] = _ABIDUMP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VTableEntry = _reflection.GeneratedProtocolMessageType('VTableEntry', (_message.Message,), dict(
  DESCRIPTOR = _VTABLEENTRY,
  __module__ = 'VndkAbiDump_pb2'
  # @@protoc_insertion_point(class_scope:android.vts.VTableEntry)
  ))
_sym_db.RegisterMessage(VTableEntry)

VTable = _reflection.GeneratedProtocolMessageType('VTable', (_message.Message,), dict(
  DESCRIPTOR = _VTABLE,
  __module__ = 'VndkAbiDump_pb2'
  # @@protoc_insertion_point(class_scope:android.vts.VTable)
  ))
_sym_db.RegisterMessage(VTable)

AbiDump = _reflection.GeneratedProtocolMessageType('AbiDump', (_message.Message,), dict(
  DESCRIPTOR = _ABIDUMP,
  __module__ = 'VndkAbiDump_pb2'
  # @@protoc_insertion_point(class_scope:android.vts.AbiDump)
  ))
_sym_db.RegisterMessage(AbiDump)


# @@protoc_insertion_point(module_scope)
